### PR TITLE
Zoho Mail 

### PR DESCRIPTION
**Pull request by zohomail**
Submitting for review.

### CODE REVIEW

**Comment by sharat-developer** [comment]
Hi @zohomail, I see this Zoho mail connector is of Oauth2 authentication type.
Can you place the connector file into the path - `/custom_connector_docs/custom_connectors/oauth2/` and rename the file as `zoho_mail_connector.rb`
Also, please add **houndci-bot** as a reviewer, so that hound can validate your code as per Rubocop conventions.

**Comment by zohomail** [comment]
Hi @sharat-developer , I have renamed and moved the file. However I'm not able to request a review.

**Comment by sharat-developer** [comment]
@zohomail can you create new PR? Houndci-bot will be added as a reviewer by-default!

**Comment by zohomail** [comment]
Closing this PR and creating a new one.

**Pull request closed without merging**
