### PR TITLE
get filename from header on get_file action and add image fields to d…

### PR DESCRIPTION
**Pull request by johnhuffmanattrackvia**
…ocument actions

### CODE REVIEW

**Comment by johnhuffmanattrackvia** [comment]
Talk to John H at TrackVia before merging.  I want to know if changing the output field structure on an action will effect running recipes.

**Comment by carlyfrederick-workato** [comment]
@bennettgo John from TrackVia is unable to assign reviewers - can you please review? And also please note John's comment above to consult him before merging on `I want to know if changing the output field structure on an action will effect running recipes.`

**Comment by bennettgo** [comment]
@johnhuffmanattrackvia Hi John, sorry for the late review. Adding new input fields should not be an issue. I have taken a look at the code and made a few changes and left out some which didn't seem necessary (changing the name of the picklist from `document_fields` to `file_fields`. 

Check out the difference here - https://www.diffchecker.com/xNtF4Pz9

**Comment by johnhuffmanattrackvia** [comment]
@bennettgo the reason for the change from document_fields to file_fields was because there is a small change that also allows image type fields in TrackVia to be pulled.  file_fields is a more accurate description because now both of TrackVia's file type fields can be fetched.

**Comment by bennettgo** [comment]
@johnhuffmanattrackvia Alright! i've changed the naming of the picklist. Other than that, would the code be alright for me to send over to it being merged?

**Comment by johnhuffmanattrackvia** [comment]
@bennettgo this looks good to me. lets merge it

**Comment by johnhuffmanattrackvia** [comment]
@bennettgo can we merge this into your master branch?

**Comment by bennettgo** [comment]
@johnhuffmanattrackvia merged! sorry!

**Pull request merged**
