### PR TITLE
adding a hotfix for an inconsistent platform header

### PR DESCRIPTION
**Pull request by johnhuffmanattrackvia**

### CODE REVIEW

**Comment by bennettgo** [comment]
@johnhuffmanattrackvia could you give some examples of a content_disposition headers so we can see what the change in logic does?

**Comment by johnhuffmanattrackvia** [comment]
@bennettgo in some instances, our platform returns the filename as a header value that looks like this `attachment; filename="picture.jpg"` and in other cases it returns a value that looks like this `attachment; filename=picture.jpg`

note the lack of consistent behavior in wrapping the filename with double quotes.  The logic change instead splits the header value on `=` and accounts for the inconsistent behavior.

**Comment by johnhuffmanattrackvia** [comment]
@bennettgo can you merge this so the repo reflects the hot fix being pushed to prod?

**Comment by johnhuffmanattrackvia** [comment]
@bennettgo still looking to get this merged

**Comment by bennettgo** [comment]
@johnhuffmanattrackvia Done! sorry

**Pull request merged**
